spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: lobby-service
            uri: http://localhost:9092
            predicates:
              - Path=/api/v1/lobby/**
            filters:
              - StripPrefix=3
              - name: CircuitBreaker
                args:
                  name: lobbyServiceCircuitBreaker
                  fallbackUri: forward:/fallback

          - id: game-service
            uri: http://localhost:9091
            predicates:
              - Path=/api/v1/game/**
            filters:
              - name: CircuitBreaker
                args:
                  name: gameServiceCircuitBreaker
                  fallbackUri: forward:/fallback

          - id: auth-service
            uri: http://localhost:9093
            predicates:
              - Path=/api/v1/auth/**
            filters:
              - StripPrefix=3
              - name: CircuitBreaker
                args:
                  name: authServiceCircuitBreaker
                  fallbackUri: forward:/fallback

resilience4j:
  circuitbreaker:
    instances:
      lobbyServiceCircuitBreaker:
        slidingWindowSize: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 1000ms
        permittedNumberOfCallsInHalfOpenState: 2

      gameServiceCircuitBreaker:
        slidingWindowSize: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 1000ms
        permittedNumberOfCallsInHalfOpenState: 2

      authServiceCircuitBreaker:
        slidingWindowSize: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 1000ms
        permittedNumberOfCallsInHalfOpenState: 2